server {
    listen 8080;
    server_name localhost;

    root /tmp/;
    index ../home/habenydi/webserv.1337/www/html/index.html;
    error_page 404 /404.html;
    client_max_body_size 1000000;


    Cgi_Interpreter .py /usr/bin/python3
    Cgi_Interpreter .pl /usr/bin/perl
    Cgi_Interpreter .sh /usr/bin/sh
}
