include mime.types

server {
    listen 8080;
    server_name localhost;

    root /tmp/;
    index ../home/habenydi/webserv.1337/www/html/index.html;
    error_page 404 /404.html;
    client_max_body_size 1000000;


    cgi_interpreter .py /usr/bin/python3
    cgi_interpreter .pl /usr/bin/perl
    cgi_interpreter .sh /usr/bin/sh
}
