include mime.types
server {

    listen 8080;
    listen 8081;
    server_name SHLO7serv;
    host 127.0.0.1;

    root ./www;
    index index.html;
    error_page 404 /html/error/404.html;
    error_page 400 /html/error/400.html;
    error_page 500 /html/error/500.html;
    error_page 405 /html/error/405.html;
    return /google https://www.google.com;

    client_max_body_size 1000000;

    location / {
        root ./www/html;
    }
    location /html/error {
        # root ./www/html;
        autoindex on;
    }


    cgi_interpreter .py /usr/bin/python3
    cgi_interpreter .pl /usr/bin/perl
    cgi_interpreter .sh /usr/bin/sh
}

server {

    listen 1337;
    server_name SHLO7serv;
    host 127.0.0.1;

    root ./www;
    index index.html;
    error_page 404 /html/error/404.html;
    error_page 400 /html/error/400.html;
    error_page 500 /html/error/500.html;
    error_page 405 /html/error/405.html;
    return /google https://www.google.com;

    client_max_body_size 1000000;

    location / {
        root ./www/html;
    }
    location /html/error {
        # root ./www/html;
        autoindex on;
    }


    cgi_interpreter .py /usr/bin/python3
    cgi_interpreter .pl /usr/bin/perl
    cgi_interpreter .sh /usr/bin/sh
}
