server {
    listen 8080;
    server_name localhost;

    root ./www;
    index index.html;
    error_page 400 /400.html;
    error_page 401 /401.html;
    error_page 402 /402.html;
    error_page 403 /403.html;
    error_page 404 /404.html;
    client_max_body_size 1000000;

    location /html {
        root ./www/html;
        autoindex off;
    }

    Cgi_Interpreter .py /usr/bin/python3
    Cgi_Interpreter .pl /usr/bin/perl
    Cgi_Interpreter .sh /usr/bin/sh
}
